import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor:"#FFF",
  },
  text: {
    marginLeft: 30,
    top:-50,
    paddingBottom: 5,
    color: '#A6A5A7',
  },
    datePickerButton: {
      backgroundColor: '#fff',
      padding: 5,
      marginHorizontal: 15,
      borderRadius: 30,
      borderWidth: 1,
      borderColor: '#ccc',
      paddingLeft: 20,
      paddingTop: 10,
      marginBottom: 10,
    },
    datePickerButtonText: {
      fontSize: 16,
      marginBottom: 10,
      justifyContent: 'center',
      color: '#555',
    },
  signup_title: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  signup_text: {
    marginBottom: 10,
    fontSize: 13,
    marginLeft: 30,
    color: '#555',
  },
  image: {
    width: '100%',
    height: '50%',
    top: -80,
    resizeMode: 'contain',
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 20,
    top: -50,
  },
  addPlantTabContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
    top: -50,
  },
  monitorTabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 20,
  },
  tab: {
    paddingVertical: 10,
    top: 0,
  },
  selectParameterText:{
    fontSize:10,
    color:"#000",
  },
  tabText: {
    fontSize: 16,
    color: '#000',
  },
  activeTabText: {
    fontSize: 16,
    color: '#ff0000',
    borderBottomWidth: 2,
    borderBottomColor: '#ff0000',
  },
  sample: {
    borderColor: '#555',
    borderWidth: 2,
  },
  input: {
    top:-50,
    height: 50,
    marginHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 30,
    marginBottom: 10,
    textAlignVertical: "center",
    paddingLeft: 25,
  }, 
  plantInput: {
    top:-50,
    height: 50,
    marginHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 30,
    marginBottom: 10,
  },
  signup_input: {
    height: 50,
    marginHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 30,
    marginTop: 10,
    marginBottom: 10,
    textAlignVertical: "center",
    paddingLeft: 25,
  },
  
  linkContainer: {
    top:-50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  linkText: {
    color: '#ff0000',
    marginHorizontal: 30,
    alignContent :'center',
    textAlign: 'center',
  },  
 button: {
    top:-40,
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    marginHorizontal: 20,
  },
  businessButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    marginHorizontal: 20,
  },
  buttonText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: 'bold',
  },
  signup_button: {
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    marginHorizontal: 15,
    marginTop:40,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 20,
    height: 55,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
  },
  registerText: {
    top:-40,
    color: '#000',
    textAlign: 'center',
    paddingBottom: 50,
  },
  centerContainer: {
    justifyContent: 'center',
    top:200,
    alignItems: 'center',
    width: '100%',
  },
  scrollView: {
    marginVertical: 20,
  },
 scrollViewContent: {
  flexGrow: 1,
  padding: 0, 
  margin: 0, 
},
 logoContainer: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 8,
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4, 
    marginBottom :  10,
  },
  logoText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  progressBarContainer: {
    height: 5,
    width: '100%',
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    marginVertical: 20,
  },
  progressBar: {
    width: '30%', 
    height: '100%',
    backgroundColor: '#3B5998',
    borderRadius: 2,
  },

appBar: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingHorizontal: 16,
  height: 56,
  backgroundColor: '#fff',
  borderBottomWidth: 0,
},

appBarTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#000',
},

iconButton: {
  width: 40,
  height: 40,
  justifyContent: 'center',
  alignItems: 'center',
},

searchContainer: {
  paddingHorizontal: 16,
  paddingVertical: 8,
  backgroundColor: '#fff',
},

searchBox: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#f5f5f5',
  borderRadius: 8,
  paddingHorizontal: 12,
  height: 40,
},

searchIcon: {
  marginRight: 8,
},

searchInput: {
  flex: 1,
  fontSize: 16,
  color: '#000',
  padding: 0,
  height: '100%',
},

totalPlantsContainer: {
  backgroundColor: '#FFF', 
  padding: 15,
  borderRadius: 8,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  marginHorizontal: 15,
  shadowOpacity: 0.2,
  shadowRadius: 4,
  elevation: 4, 
  marginBottom: 20, 
},
totalPlantsTitle: {
  fontSize: 16,
  marginLeft: 10,
  color: '#000', 
},
heading: {
  fontSize: 24,
  fontWeight: 'bold',
  marginBottom: 10,
  textAlign: 'center', 
},
line: {
  height: 1,
  backgroundColor: '#CCC',
  marginVertical: 10
},
plantStatusContainer: {
  flexDirection: 'row',
  alignItems: 'center',
},
plantStatusText: {
  fontSize: 16,
  marginLeft: 10,
  marginBottom:10,
},
totalPlantsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItem: {
    marginHorizontal:10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    marginLeft: 10,
  },
  header: {
    alignItems: 'center',
    marginVertical: 20,
  },
  headerTitle: {
    alignContent: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    fontSize: 18,
    fontWeight: 'bold',
  },
  headerSubtitle: {
    fontSize: 16,
    color: 'gray',
  },
tab: {
  paddingVertical: 10,
  paddingHorizontal: 15,
},
tabText: {
  fontSize: 16,
  color: '#000',
},

noAlertContainer: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
},
noAlertImage: {
  width: 100,
  height: 100,
  marginBottom: 20,
},
noAlertText: {
  fontSize: 20,
  color: '#A9A9A9',
},
noPlantContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  noPlantText: {
    fontSize: 20,
    color: '#A9A9A9',
  }, appBarIcon: {
    padding: 10,
  },
  tabBarContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
    backgroundColor: '#FFF', 
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: '#FFF', 
    },
    arrowIcon: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignContent: 'center',
      marginLeft:30,
    },
    watchlistContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 20,
},
watchlistLeft: {
    flexDirection: 'row',
    alignItems: 'center',
},
watchlistText: {
    fontSize: 16,
    color: '#000',
    marginLeft: 8,
},
arrowIcon: {
    color: '#757575',
},
  calendarContainer: {
    marginVertical: 20,
    marginBottom: 150,
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    marginHorizontal: 15,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,  
  },
    changeImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    padding: 10,
    borderRadius: 8,
  },
  removeImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
  },
  filterContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      marginVertical: 10,
    },
    filterButton: {
      backgroundColor: '#FFDCDC',
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 20,
    },
    filterText: {
      color: '#FFF',
      fontSize: 16,
      fontWeight: 'bold',
    },
addplantTitle: {
  fontSize: 20,
  fontWeight: 'bold',
  textAlign: 'center',
  flex: 1,
},
imageUploadContainer: {
  width: '100%',
  height: 200,
  backgroundColor: '#f0f0f0',
  borderRadius: 8,
  marginBottom: 50,
  overflow: 'hidden',
},
plantImage: {
  width: '100%',
  height: '100%',
},
imagePlaceholder: {
  width: '100%',
  height: '100%',
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#f0f0f0',
},
imagePlaceholderText: {
  marginTop: 8,
  color: '#666',
  fontSize: 16,
}, plantCard: {
  backgroundColor: '#fff',
  borderRadius: 8,
  marginBottom: 12,
  padding: 16,
  elevation: 2,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
},
plantCardImage: {
  width: '100%',
  height: 150,
  borderRadius: 8,
  marginBottom: 12,
},
plantCardContent: {
  flex: 1,
},
plantName: {
  fontSize: 18,
  fontWeight: 'bold',
  marginBottom: 4,
},
plantLocation: {
  fontSize: 16,
  color: '#666',
},
expandedContent: {
  marginTop: 12,
  paddingTop: 12,
  borderTopWidth: 1,
  borderTopColor: '#eee',
},
emptyState: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  paddingVertical: 40,
},
emptyStateText: {
  marginTop: 12,
  fontSize: 16,
  color: '#666',
},  editButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#ff0000',
  padding: 8,
  borderRadius: 4,
  marginTop: 12,
  alignSelf: 'flex-start',
},
editButtonText: {
  color: '#fff',
  marginLeft: 8,
  fontSize: 14,
  fontWeight: '500',
},
profileSection: {
  alignItems: 'center',
  paddingVertical: 20,
},
profileImageContainer: {
  marginBottom: 16,
},
profileImage: {
  width: 250,
  height: 250,
  borderRadius: 200,
},
headerTitle: {
  fontSize: 24,
  fontWeight: 'bold',
  marginBottom: 4,
},
headerSubtitle: {
  fontSize: 16,
  color: '#666',
  marginBottom: 16,
},
imageButtonsContainer: {
  flexDirection: 'row',
  justifyContent: 'center',
  gap: 10,
},
imageButton: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#ff0000',
  paddingVertical: 8,
  paddingHorizontal: 16,
  borderRadius: 20,
  gap: 8,
},
deleteButton: {
  backgroundColor: '#666',
},
buttonText: {
  color: 'white',
  fontSize: 14,
  fontWeight: '500',
},
menuItem: {
  flexDirection: 'row',
  alignItems: 'center',
  padding: 16,
  backgroundColor: '#fff',
  borderRadius: 8,
  marginBottom: 8,
},
menuText: {
  flex: 1,
  marginLeft: 16,
  fontSize: 16,
},
modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0, 0, 0, 0.5)',
  justifyContent: 'flex-start',
},
modalContent: {
  backgroundColor: '#fff',
  marginTop: 150,
  marginHorizontal: 20,
  borderRadius: 8,
  padding: 16,
},
modalItem: {
  paddingVertical: 12,
  borderBottomWidth: 1,
  borderBottomColor: '#eee',
},
modalItemText: {
  fontSize: 16,
  color: '#333',
},
selectedModalItem: {
  color: '#ff0000',
  fontWeight: 'bold',
},
sortTabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal:25,
  },
  sortTabText: {
    fontSize: 10,
    color: '#666',
    marginRight: 2,
  },
  radioGroup: {
    marginBottom: 20,
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  radio: {
    marginHorizontal: 10,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#000',
    marginRight: 10,
  },
  radioSelected: {
    marginHorizontal: 10,
    backgroundColor: '#FF0000',
    borderColor: '#FFDCDC',
  },
  text2: {
    fontSize: 16,
    top:-50,
    marginHorizontal: 30,
    marginTop:40,
    color: '#A6A5A7',
  },
  radioText: {
    fontSize: 16,
    color: '#333',
  },
  moreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginVertical: 8,
  },
  moreButtonText: {
    fontSize: 16,
    color: '#666',
    marginRight: 4,
  },
  currencySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 16,
  },
  currencyText: {

    fontSize: 20,
    top:-50,
    marginHorizontal: 30,
    color: '#333',
  },
  alertSafeArea: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight - 10 : 0,
  },
  alertAppBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    top:-20,
    paddingVertical: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  alertTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
  },
  alertTabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 20,
    top: -30,
  },
  componentContainer: {
    marginBottom: 20,
    borderRadius: 8,
    backgroundColor: '#fff',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  toggleButton: {
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: 'center',
  },
  toggleText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  settingSection: {
    marginBottom: 20,
  },
  toggleButton: {
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  toggleButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  settingsContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  settingOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 12,
  },
  settingRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingRightText: {
    fontSize: 16,
    color: '#999',
    marginRight: 8,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    marginTop: 20,
    backgroundColor: '#fff',
    gap: 8,
  },
  logoutText: {
    color: '#FF6B6B',
    fontSize: 16,
    fontWeight: '500',
  },
});

export default styles;